      - name: Kamera + radyo SSH101
        env:
          SSH101_KEY: ${{ secrets.SSH101_KEY }}
        run: |
          ffmpeg \
            -hide_banner \
            -loglevel info \
            -analyzeduration 30M \
            -probesize 50M \
            -fflags +genpts \
            -reconnect 1 \
            -reconnect_streamed 1 \
            -reconnect_delay_max 5 \
            -i "https://kamerayayin.ibb.istanbul/turistikcam/buyukcamlica.stream/chunklist_w607999958.m3u8" \
            -reconnect 1 \
            -reconnect_streamed 1 \
            -reconnect_delay_max 5 \
            -i "https://sslyayin.netyayin.net/aksarayinsesi/stream/" \
            -map 0:v:0 \
            -map 1:a:0 \
            -c:v libx264 \
            -preset ultrafast \
            -tune zerolatency \
            -pix_fmt yuv420p \
            -r 25 \
            -s 1280x720 \
            -g 50 \
            -keyint_min 50 \
            -sc_threshold 0 \
            -b:v 1800k \
            -maxrate 2000k \
            -bufsize 4000k \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -f flv \
            "rtmp://ssh101.bozztv.com/ssh101/${SSH101_KEY}"
