name: Gercek Yayin Testi - Aksaray Sesi

on:
  workflow_dispatch:

jobs:
  stream-test:
    runs-on: ubuntu-24.04

    steps:

      # ==========================================
      # 1 - FFMPEG
      # ==========================================

      - name: FFmpeg kontrolu
        run: |
          echo "======================================"
          echo "FFMPEG KONTROL"
          echo "======================================"

          if command -v ffmpeg >/dev/null 2>&1; then
            echo "FFmpeg zaten kurulu."
          else
            echo "FFmpeg bulunamadi."

            echo "FFmpeg kuruluyor..."

            timeout 180 sudo apt-get update -y
            timeout 180 sudo apt-get install -y ffmpeg
          fi

          echo ""
          echo "FFmpeg versiyonu:"
          ffmpeg -version | head -n 1


      # ==========================================
      # 2 - DNS
      # ==========================================

      - name: SSH101 DNS testi
        run: |
          echo "======================================"
          echo "SSH101 DNS"
          echo "======================================"

          getent hosts ssh101.bozztv.com

          echo "DNS OK"


      # ==========================================
      # 3 - SSH101 PORT
      # ==========================================

      - name: SSH101 port testi
        run: |
          echo "======================================"
          echo "SSH101 TCP 1935"
          echo "======================================"

          timeout 10 bash -c \
          'cat < /dev/null > /dev/tcp/ssh101.bozztv.com/1935'

          echo "TCP 1935 OK"


      # ==========================================
      # 4 - KAMERA TEST
      # ==========================================

      - name: Kamera test
        run: |
          echo "======================================"
          echo "BUYUK CAMLICA KAMERA TEST"
          echo "======================================"

          timeout 30 ffmpeg \
            -hide_banner \
            -loglevel info \
            -i "https://kamerayayin.ibb.istanbul/turistikcam/buyukcamlica.stream/chunklist_w607999958.m3u8" \
            -t 10 \
            -map 0:v:0 \
            -f null -

          echo ""
          echo "KAMERA OK"


      # ==========================================
      # 5 - AKSARAY SESI TEST
      # ==========================================

      - name: Aksaray Sesi test
        run: |
          echo "======================================"
          echo "AKSARAY SESI TEST"
          echo "======================================"

          timeout 30 ffmpeg \
            -hide_banner \
            -loglevel info \
            -analyzeduration 10M \
            -probesize 20M \
            -i "https://sslyayin.netyayin.net/aksarayins
