name: Dosya Kontrol

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Tum dosyalari listele
        run: |
          echo "=== REPOSITORY ==="
          pwd
          echo "=== DOSYALAR ==="
          find . -maxdepth 3 -type f -print
          echo "=== IMAGE DOSYALARI ==="
          find . -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png"
