name: Aksaray Sesi Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FFmpeg kontrol
        run: ffmpeg -version

      - name: Dosyaları kontrol et
        run: |
          ls -lah
          file image.jpg
          cat start.sh
